# Generated by Django 4.2.13 on 2024-06-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='markdown',
            field=models.TextField(blank=True),
        ),
    ]
