# Generated by Django 4.2.13 on 2024-06-14 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_project_priority_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursiveList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='personal.recursivelist')),
            ],
        ),
    ]
