# Generated by Django 5.1.3 on 2024-11-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_infinitelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfiniteList',
        ),
        migrations.DeleteModel(
            name='RecursiveList',
        ),
    ]
