# Generated by Django 4.2.13 on 2024-06-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_project_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
