# Generated by Django 4.2.13 on 2024-06-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_recursivelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursivelist',
            name='collapsed',
            field=models.BooleanField(default=True),
        ),
    ]
